### ISSUE TITLE
Test Alert API to Website mismatch

### ISSUE THREAD

**Issue by nadand** [cpicpgx/cpic-data#15] opened 2021-08-12 16:18 UTC
While using the API we have noticed that the content in test_alert.alerttext does not match what is available on the website to download. It seems that API returns the same alerttext for different populations while on the website it is different. 

For example the CYP2C19 Post test /test_alert?drugid=eq.RxNorm:121243&lookupkey=cs.{"CYP2C19": "Rapid Metabolizer"}&select=id,population,cdscontext,alerttext,drug(name)  returns

```json
 [
    {
        "id": 875274,
        "population": "pediatrics",
        "cdscontext": "Post-test",
        "alerttext": [
            "Based on the genotype result, this patient is predicted to be a CYP2C19 rapid metabolizer, and the probability of attainment of therapeutic concentrations is variable. Initiate therapy with recommended standard of care dosing. Meticulous therapeutic drug monitoring to titrate dose to therapeutic trough concentrations is critical due to large variability in trough concentrations in rapid metabolizers. Please consult a clinical pharmacist for more information."
        ],
        "drug": {
            "name": "voriconazole"
        }
    },
    {
        "id": 875283,
        "population": "adults",
        "cdscontext": "Post-test",
        "alerttext": [
            "Based on the genotype result, this patient is predicted to be a CYP2C19 rapid metabolizer, and the probability of attainment of therapeutic concentrations is variable. Initiate therapy with recommended standard of care dosing. Meticulous therapeutic drug monitoring to titrate dose to therapeutic trough concentrations is critical due to large variability in trough concentrations in rapid metabolizers. Please consult a clinical pharmacist for more information."
        ],
        "drug": {
            "name": "voriconazole"
        }
    }
]
```

While to content on the website is:

![image](https://user-images.githubusercontent.com/6733280/129230457-ec1efa75-ed19-4a41-a1fa-c04f16ebf3ff.png)

**Comment by whaleyr** [comment] 2021-08-13 15:42
You're right, the text is technically different but the content is the same.

For pediatric population:
- the words `Rapid Metabolizer,` have been changed to `rapid metabolizer`
- the `b` footnote character has been removed since it has no context in the API result

For adult population:
- the words `Rapid Metabolizer,` have been changed to `rapid metabolizer`
- the text `suspected or document fungal species` has been corrected to `suspected or documented fungal species`
- the `b` footnote character has been removed since it has no context in the API result

You may see other corrections for punctuation, capitalization, or misspellings like this elsewhere in API responses.

**Comment by whaleyr** [comment] 2021-08-13 17:59
It was just brought to my attention that I misunderstood your initial post. You're saying the alerttext array is literally the same between the 2 populations on the API response. I'm looking into it.

**Comment by whaleyr** [comment] 2021-08-13 19:13
I looked into it and found a bug in our test alert importer. Thanks for bringing this to our attention. It's very helpful when members of the community help point out these issues.

I'm deploying the code out to the server soon and the data should be fixed within the next few hours.

**Comment by whaleyr** [comment] 2021-08-13 20:24
I just confirmed the data is updated on the API for the example call in the OP so I'm closing this issue.

**Closed by whaleyr** 2021-08-13 20:24 UTC
